### ISSUE TITLE
Suggest revise.

### ISSUE THREAD

**Issue by Droidtown** [shendongCathy/Legal_CCU_LawNLP#2]
https://github.com/shendongCathy/Legal_CCU_LawNLP/blob/2426565622bbad0b5047e2f95880d3e784493980/getTEXT.py#L23C1-L27C22

from ArticutAPI import Articut
import json
try:
    accountDICT = json.load(open("account.info", encoding="utf-8"))
except:
    accountDICT = {"username":"", "apikey":""}

```
def articut(inputSTR, accountDICT):
    articut = Articut(username=accountDICT["username"], apikey=accountDICT["apikey"])
    resultDICT = articut.parse(inputSTR)

    return resultDICT
```

**Comment by shendongCathy** [comment]
Done.
